module.exports = {
	baseUrl: 'http://121.41.19.238:8555',
	appVersion: 23,
	entities: [
		"t_serviceworkorder",
		"t_service",
		"t_complaint",
		"t_consult",
		"t_service_acitivity",
		"t_servicework",
		"t_notwork",
		"t_reminder",
		"t_site_back",
		"t_servicesend",
		"t_recall",
		"t_servicedelete",
		"t_servicerepair",
		"t_details",
		"t_firstgascheck",
		"t_failure",
		"t_failurecase",
		"t_baseuserinfo",
		"t_repairimg",
		"t_detailimg",
		"t_substitution",
		"t_notice",
		"t_check_paper",
		"t_paper_overall_imgs",
		"t_devices_items_lists",
		"t_check_plan_item",
		"t_check_plan",
		"t_phone_state",
		"t_plan_item_meter",
		"t_plan_item_device",
		"t_device_info",
		"t_defect_info",
		"t_devices_items",
		"t_paper_devices",
		"t_telchangematter",
		"t_phonehandplan",
		"t_phonehandplanimgs",
		"t_apply",
		"t_app_apply",
		"t_phone_state"
	]
}
